### ISSUE TITLE
Export implicit config dependencies

### ISSUE THREAD

**Issue by darthsteven** [computerminds/cm_config_tools#18]
I have config A

Config A depends upon config Z.

If I try and install/import config A and I don't have config Z, Drupal will complain, rightly.

Where we have this dependency chain, we should export the config we can implicitly determine we should.
This would feel a tiny bit like D7 features, in that I should be able to list my top level config A, and get X, Y and Z.

Note that I suppose that if the config depends on a _module_ that provides some config in it's config/install, then we don't need to implicitly export that config.

**Comment by stevetweeddale** [comment]
@anotherjames did we already get this in https://github.com/computerminds/cm_config_tools/pull/1?

**Comment by anotherjames** [comment]
@stevetweeddale #1 has done the majority of the necessary work, but I would not consider it 'done' because there would still be enough problems with it that I would like to work on before it starts being used for real-life projects please.

For example: #6, #5 (and possibly even #3).

**Comment by anotherjames** [comment]
This has now been done in f5241907a5e76464259d27788602f1130a12d0f0!
