### ISSUE TITLE
DEPRECATE

### ISSUE THREAD

**Issue by anotherjames** [computerminds/cm_config_tools#34]
We should mark this project as deprecated. See https://support.computerminds.co.uk/issues/45097

Good links that I've told @AF about, for reference, at least:

https://www.prometsource.com/blog/configuration-split-managing-drupal-8-configuration-different-environments

http://glassdimly.com/blog/tech/planet-drupal-drupal-8-configuration-management-config-split/config-management-roundup

https://blog.liip.ch/archive/2017/04/07/advanced-drupal-8-cmi-workflows.html

https://blt.readthedocs.io/en/8.x/readme/config-split/ (specific to acquia's BLT workflow, but very good documentation for applying it to our own)

https://www.isovera.com/blog/practical-guide-configuration-management-drupal-8 (has a handy section on config_split that explains some of its more obscure stuff like the greylist. I think that's written by the peeps that made the module too.)

https://www.advomatic.com/blog/using-configuration-split-to-have-dev-only-configuration-in-drupal-8 (other links are probably more than enough)

**Comment by darthsteven** [comment]
If you happen to need to get a list of all the config not managed by cm_config_tools, then #35 might be for you.

**Comment by anotherjames** [comment]
I've added some deprecated topics to the repo, and updated the description. I'm not aware of better ways to mark a repo on github as deprecated. There's only a few of our projects left using cm_config_tools now.
